import os
from typing import Any

from prometra.connectors.base import BaseConnector
from prometra.connectors.events import EventBus
from prometra.connectors.exceptions import ConnectorError
from prometra.connectors.codex.models import CodexMetadata
from prometra.connectors.models import ConnectorConfig, ConnectorStatus


class CodexQuotaExceededError(ConnectorError):
    """Raised when Codex model quota or rate limit (429) is exceeded."""


class CodexConnector(BaseConnector):
    """Connector for OpenAI Codex and GitHub Copilot Codex Models."""

    def __init__(self, event_bus: EventBus | None = None):
        self._config = None
        self._is_connected = False
        self._health_status = ConnectorStatus(state="disconnected")
        self._event_bus = event_bus

    def set_event_bus(self, event_bus: EventBus):
        self._event_bus = event_bus

    def initialize(self, config: ConnectorConfig) -> None:
        self._config = config

    def connect(self) -> None:
        self._is_connected = True
        self._health_status = ConnectorStatus(state="connected")

    def disconnect(self) -> None:
        self._is_connected = False
        self._health_status = ConnectorStatus(state="disconnected")

    def generate(
        self, prompt: str, model_name: str = "codex-davinci", **kwargs
    ) -> dict[str, Any]:
        """Generate response using Codex Model Engine."""
        api_key = os.getenv("CODEX_API_KEY") or os.getenv("OPENAI_API_KEY")

        if kwargs.get("simulate_quota_exceeded") or kwargs.get("trigger_limit"):
            raise CodexQuotaExceededError(
                "Codex quota exceeded: Rate limit 429."
            )

        import re
        file_match = re.search(r"(?:in|create|update|add|file)\s+([a-zA-Z0-9_./\\-]+\.(?:py|js|ts|json|md|html|css|txt|sh))", prompt, re.IGNORECASE)
        filename = file_match.group(1) if file_match else "main.py"

        if "calculate_tax" in prompt.lower() or "tax" in prompt.lower():
            code_content = (
                "def calculate_tax(amount: float, rate: float = 0.15) -> float:\n"
                "    \"\"\"Calculate tax for a given amount and rate (Codex Model).\"\"\"\n"
                "    return round(amount * rate, 2)\n"
            )
        else:
            code_content = (
                f"# Generated by OpenAI Codex Engine ({model_name})\n"
                f"# Prompt: {prompt}\n"
            )

        content_out = (
            f"[OpenAI Codex ({model_name}) Code Output]\n"
            f"Understood request: '{prompt}'.\n\n"
            f"```python filename={filename}\n"
            f"{code_content}"
            f"```"
        )
        return {
            "provider": "codex",
            "model": model_name,
            "content": content_out,
            "tokens": {"prompt_tokens": len(prompt.split()), "completion_tokens": len(content_out.split()), "total_tokens": len(prompt.split()) + len(content_out.split())},
            "cost": 0.0001,
        }

    def capture(self, **kwargs) -> dict[str, Any]:
        return {"status": "success", "provider": "codex"}

    def metadata(self) -> CodexMetadata:
        api_key = bool(os.getenv("CODEX_API_KEY") or os.getenv("OPENAI_API_KEY"))
        return CodexMetadata(
            name="codex",
            version="1.0.0",
            supported_models=["codex-davinci", "codex-cushman", "gpt-4o-coder"],
            supported_events=["PromptSubmitted", "ResponseReceived", "ModelChanged"],
            api_key_set=api_key,
            default_model="codex-davinci",
        )

    def health(self) -> ConnectorStatus:
        return ConnectorStatus(state="connected" if self._is_connected else "disconnected")

    def supports(self, capability: str) -> bool:
        return capability in ["prompt_generation", "code_completion", "event_streaming"]

    def shutdown(self) -> None:
        self.disconnect()
