"""Prometra Live Local MCP Server.

Runs a lightweight HTTP JSON-RPC 2.0 MCP server on http://localhost:8000/mcp.
- Open http://localhost:8000/mcp in your browser to see the live server status page.
- Send JSON-RPC POST requests via Prometra CLI (`prometra vibe --primary-model mcp`).
"""

import json
from http.server import HTTPServer, BaseHTTPRequestHandler

HOST = "localhost"
PORT = 8000

class MCPRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        """Handle browser HTTP GET requests."""
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.end_headers()
        html = """<!DOCTYPE html>
<html>
<head>
    <title>Prometra MCP Server</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #f8fafc; text-align: center; padding-top: 80px; }
        .card { background: #1e293b; border: 1px solid #334155; border-radius: 12px; max-width: 550px; margin: 0 auto; padding: 40px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }
        .status { display: inline-block; padding: 8px 16px; background: #059669; color: white; border-radius: 20px; font-weight: bold; margin-bottom: 20px; }
        code { background: #090d16; padding: 4px 8px; border-radius: 6px; color: #38bdf8; }
    </style>
</head>
<body>
    <div class="card">
        <div class="status">🟢 MCP SERVER ACTIVE</div>
        <h2>Prometra Model Context Protocol (MCP) Server</h2>
        <p>Listening on <code>http://localhost:8000/mcp</code></p>
        <hr style="border-color: #334155; margin: 20px 0;">
        <p style="color: #94a3b8; font-size: 14px;">
            Ready to receive JSON-RPC 2.0 HTTP POST requests from <code>prometra vibe --primary-model mcp</code>
        </p>
    </div>
</body>
</html>
"""
        self.wfile.write(html.encode("utf-8"))

    def do_POST(self):
        """Handle MCP JSON-RPC POST requests."""
        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length).decode("utf-8")

        try:
            req = json.loads(body)
            req_id = req.get("id", 1)
            params = req.get("params", {})
            args = params.get("arguments", {})
            prompt = args.get("prompt", "")
            model = args.get("model", "gemini-via-mcp")

            response_content = (
                f"[Live Local MCP Server ({model})]\n"
                f"Understood request: '{prompt}'.\n\n"
                f"```python filename=main.py\n"
                f"# Generated by Live MCP Server ({model})\n"
                f"# Prompt: {prompt}\n"
                f"```"
            )

            resp_payload = {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "content": response_content
                }
            }
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps(resp_payload).encode("utf-8"))

        except Exception as e:
            self.send_response(500)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            err_payload = {"jsonrpc": "2.0", "id": 1, "error": {"code": -32603, "message": str(e)}}
            self.wfile.write(json.dumps(err_payload).encode("utf-8"))

    def log_message(self, format, *args):
        """Clean log messages."""
        print(f"[MCP Server] {self.address_string()} - {format % args}")

def run_server():
    server = HTTPServer((HOST, PORT), MCPRequestHandler)
    print(f"🚀 Prometra MCP Server running at http://{HOST}:{PORT}/mcp")
    print("Press Ctrl+C to stop.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping MCP Server...")
        server.server_close()

if __name__ == "__main__":
    run_server()
